project:
  type: book
  title: "Practical One"
  output-dir: _book
  
book: 
  chapters: 
    - index.qmd
    - Prac_day_1.qmd
    
    
website: 
  navbar:
    left: 
      - href: Prac_day_1.qmd
        text: Home