project:
  type: book
  title: "Practical One"
  output-dir: _book
  
book: 
  chapters: 
    - index.qmd
    - Prac_day_1.qmd
    - Practical_Day_four.qmd
    - Prac2.qmd
    
    
website: 
  navbar:
    left: 
      - href: Prac_day_1.qmd
        text: Home
      - href: Practical_Day_four.qmd
        text: Day four
      - href: Prac2.qmd
        text: Practical Two