---
title: "PracticalOneQuarto"
author: "Comfortella"
format: html
---

\
##SetUp

```{r}
#|  echo: true
raw_data <- airquality

```

##Cleaned Data

```{r}
#|  echo: true
cleaned_data <- na.omit(raw_data)
tmp <- cleaned_data[[4]]
tmp
ozn <- cleaned_data[[1]] 
ozn
```

##Temperature

```{r}
#|  echo: true
mean_tmp <- mean(tmp)
mean_tmp 
sd_tmp <- sd(tmp)
sd_tmp 
min_tmp <- min(tmp)
min_tmp
max_tmp<-max(tmp) 
max_tmp
```

##Ozone level

```{r}
#|  echo: true
mean_ozn <- mean(ozn)
mean_ozn 
sd_ozn <- sd(ozn)
sd_ozn 
min_ozn <- min(ozn)
min_ozn 
max_ozn <- max(ozn) 
max_ozn
```

##Linear Regression

##SetUp

```{r}
#|  echo: true
data(cars) 
speed <- cars$speed
dist <- cars$dist
```

##Design Matrix and response variable

```{r}
#|  echo: true
X <- cbind(1,speed) 
Y<-dist
```

\## beta estimate = \[(X^T^\*X)\^-1\]X^T^Y

```{r}
#|  echo: true
Xtrans <- t(X) 
XtransX <- Xtrans %% X 
XtransX_inv <- solve(XtransX) 
XtransY <- Xtrans %% Y 
beta_estimate <- XtransX_inv %*% XtransY
beta_estimate
```

##Linear Model

```{r}
#|  echo: true
model <- lm(dist ~ speed, data=cars) 
summary(model)
```
